# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
title: Emily Bartha

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Blog

description: 
author:
  name: Emily Bartha
  avatar: "/assets/images/avatar.png"
  github: emilyrbartha
  twitter: emilybartha
  bio: I'm Emily, a Data Scientist living and working in Austin, Texas. I like programming in R, running, and pizza. In my spare time, I organize the Aspiring Data Scientist Community Meetup in Austin.
  email_md5: 9c90f76dc77c804f02983aacb084a99d

categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
